[2022-12-02T22:14:27.877+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api manual__2022-12-02T22:09:25.803475+00:00 [queued]>
[2022-12-02T22:14:27.882+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api manual__2022-12-02T22:09:25.803475+00:00 [queued]>
[2022-12-02T22:14:27.883+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T22:14:27.884+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-12-02T22:14:27.885+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T22:14:27.891+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract_weather_api> on 2022-12-02 22:09:25.803475+00:00
[2022-12-02T22:14:27.896+0000] {standard_task_runner.py:55} INFO - Started process 355 to run task
[2022-12-02T22:14:27.898+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'extract_weather_api', 'manual__2022-12-02T22:09:25.803475+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpxei5ykx9']
[2022-12-02T22:14:27.899+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask extract_weather_api
[2022-12-02T22:14:27.939+0000] {task_command.py:376} INFO - Running <TaskInstance: extract_dag.extract_weather_api manual__2022-12-02T22:09:25.803475+00:00 [running]> on host 94f969375df6
[2022-12-02T22:14:27.975+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_dag
AIRFLOW_CTX_TASK_ID=extract_weather_api
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T22:09:25.803475+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-02T22:09:25.803475+00:00
[2022-12-02T22:14:27.976+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-02T22:14:27.977+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python extract.py']
[2022-12-02T22:14:27.988+0000] {subprocess.py:86} INFO - Output:
[2022-12-02T22:14:28.040+0000] {subprocess.py:93} INFO - python: can't open file 'extract.py': [Errno 2] No such file or directory
[2022-12-02T22:14:28.043+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-12-02T22:14:28.051+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-12-02T22:14:28.054+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_weather_api, execution_date=20221202T220925, start_date=20221202T221427, end_date=20221202T221428
[2022-12-02T22:14:28.061+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 18 for task extract_weather_api (Bash command failed. The command returned a non-zero exit code 2.; 355)
[2022-12-02T22:14:28.071+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-02T22:14:28.089+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
