[2022-12-02T21:10:09.803+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api manual__2022-12-02T21:05:08.193017+00:00 [queued]>
[2022-12-02T21:10:09.810+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api manual__2022-12-02T21:05:08.193017+00:00 [queued]>
[2022-12-02T21:10:09.811+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T21:10:09.812+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-12-02T21:10:09.812+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T21:10:09.819+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract_weather_api> on 2022-12-02 21:05:08.193017+00:00
[2022-12-02T21:10:09.824+0000] {standard_task_runner.py:55} INFO - Started process 5287 to run task
[2022-12-02T21:10:09.826+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'extract_weather_api', 'manual__2022-12-02T21:05:08.193017+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpf1h68ec1']
[2022-12-02T21:10:09.827+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask extract_weather_api
[2022-12-02T21:10:09.875+0000] {task_command.py:376} INFO - Running <TaskInstance: extract_dag.extract_weather_api manual__2022-12-02T21:05:08.193017+00:00 [running]> on host 94f969375df6
[2022-12-02T21:10:09.912+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_dag
AIRFLOW_CTX_TASK_ID=extract_weather_api
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T21:05:08.193017+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-02T21:05:08.193017+00:00
[2022-12-02T21:10:09.914+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-02T21:10:09.915+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py']
[2022-12-02T21:10:09.924+0000] {subprocess.py:86} INFO - Output:
[2022-12-02T21:10:09.985+0000] {subprocess.py:93} INFO - python: can't open file '/Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py': [Errno 2] No such file or directory
[2022-12-02T21:10:09.988+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-12-02T21:10:09.997+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-12-02T21:10:10.000+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_weather_api, execution_date=20221202T210508, start_date=20221202T211009, end_date=20221202T211010
[2022-12-02T21:10:10.007+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task extract_weather_api (Bash command failed. The command returned a non-zero exit code 2.; 5287)
[2022-12-02T21:10:10.042+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-02T21:10:10.058+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
