[2022-12-02T20:39:01.875+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api scheduled__2022-12-02T20:15:00+00:00 [queued]>
[2022-12-02T20:39:01.885+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api scheduled__2022-12-02T20:15:00+00:00 [queued]>
[2022-12-02T20:39:01.888+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T20:39:01.889+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-02T20:39:01.890+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T20:39:01.899+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract_weather_api> on 2022-12-02 20:15:00+00:00
[2022-12-02T20:39:01.904+0000] {standard_task_runner.py:55} INFO - Started process 3753 to run task
[2022-12-02T20:39:01.907+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'extract_weather_api', 'scheduled__2022-12-02T20:15:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpgzz838kh']
[2022-12-02T20:39:01.908+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask extract_weather_api
[2022-12-02T20:39:01.946+0000] {task_command.py:376} INFO - Running <TaskInstance: extract_dag.extract_weather_api scheduled__2022-12-02T20:15:00+00:00 [running]> on host 94f969375df6
[2022-12-02T20:39:01.982+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_dag
AIRFLOW_CTX_TASK_ID=extract_weather_api
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T20:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T20:15:00+00:00
[2022-12-02T20:39:01.985+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-02T20:39:01.986+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py']
[2022-12-02T20:39:01.998+0000] {subprocess.py:86} INFO - Output:
[2022-12-02T20:39:02.059+0000] {subprocess.py:93} INFO - python: can't open file '/Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py': [Errno 2] No such file or directory
[2022-12-02T20:39:02.061+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-12-02T20:39:02.070+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-12-02T20:39:02.073+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_dag, task_id=extract_weather_api, execution_date=20221202T201500, start_date=20221202T203901, end_date=20221202T203902
[2022-12-02T20:39:02.081+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task extract_weather_api (Bash command failed. The command returned a non-zero exit code 2.; 3753)
[2022-12-02T20:39:02.121+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-02T20:39:02.135+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
