[2022-12-02T20:45:00.279+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api scheduled__2022-12-02T20:30:00+00:00 [queued]>
[2022-12-02T20:45:00.284+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api scheduled__2022-12-02T20:30:00+00:00 [queued]>
[2022-12-02T20:45:00.285+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T20:45:00.286+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-02T20:45:00.287+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T20:45:00.293+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract_weather_api> on 2022-12-02 20:30:00+00:00
[2022-12-02T20:45:00.298+0000] {standard_task_runner.py:55} INFO - Started process 4052 to run task
[2022-12-02T20:45:00.300+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'extract_weather_api', 'scheduled__2022-12-02T20:30:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpx_i1c8eq']
[2022-12-02T20:45:00.301+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask extract_weather_api
[2022-12-02T20:45:00.336+0000] {task_command.py:376} INFO - Running <TaskInstance: extract_dag.extract_weather_api scheduled__2022-12-02T20:30:00+00:00 [running]> on host 94f969375df6
[2022-12-02T20:45:00.375+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_dag
AIRFLOW_CTX_TASK_ID=extract_weather_api
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T20:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T20:30:00+00:00
[2022-12-02T20:45:00.377+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-02T20:45:00.378+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py']
[2022-12-02T20:45:00.387+0000] {subprocess.py:86} INFO - Output:
[2022-12-02T20:45:00.432+0000] {subprocess.py:93} INFO - python: can't open file '/Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py': [Errno 2] No such file or directory
[2022-12-02T20:45:00.434+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-12-02T20:45:00.441+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-12-02T20:45:00.444+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_dag, task_id=extract_weather_api, execution_date=20221202T203000, start_date=20221202T204500, end_date=20221202T204500
[2022-12-02T20:45:00.452+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task extract_weather_api (Bash command failed. The command returned a non-zero exit code 2.; 4052)
[2022-12-02T20:45:00.472+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-02T20:45:00.487+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
