[2022-12-02T20:50:00.892+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api scheduled__2022-12-02T20:30:00+00:00 [queued]>
[2022-12-02T20:50:00.898+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api scheduled__2022-12-02T20:30:00+00:00 [queued]>
[2022-12-02T20:50:00.899+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T20:50:00.900+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-12-02T20:50:00.900+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T20:50:00.907+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract_weather_api> on 2022-12-02 20:30:00+00:00
[2022-12-02T20:50:00.912+0000] {standard_task_runner.py:55} INFO - Started process 4301 to run task
[2022-12-02T20:50:00.914+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'extract_weather_api', 'scheduled__2022-12-02T20:30:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpp9wz0c5i']
[2022-12-02T20:50:00.914+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask extract_weather_api
[2022-12-02T20:50:00.949+0000] {task_command.py:376} INFO - Running <TaskInstance: extract_dag.extract_weather_api scheduled__2022-12-02T20:30:00+00:00 [running]> on host 94f969375df6
[2022-12-02T20:50:00.983+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_dag
AIRFLOW_CTX_TASK_ID=extract_weather_api
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T20:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T20:30:00+00:00
[2022-12-02T20:50:00.985+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-02T20:50:00.987+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py']
[2022-12-02T20:50:00.996+0000] {subprocess.py:86} INFO - Output:
[2022-12-02T20:50:01.047+0000] {subprocess.py:93} INFO - python: can't open file '/Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py': [Errno 2] No such file or directory
[2022-12-02T20:50:01.050+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-12-02T20:50:01.058+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-12-02T20:50:01.061+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_weather_api, execution_date=20221202T203000, start_date=20221202T205000, end_date=20221202T205001
[2022-12-02T20:50:01.068+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task extract_weather_api (Bash command failed. The command returned a non-zero exit code 2.; 4301)
[2022-12-02T20:50:01.087+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-02T20:50:01.102+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
