[2022-12-02T21:21:14.615+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api manual__2022-12-02T21:21:13.937226+00:00 [queued]>
[2022-12-02T21:21:14.622+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_weather_api manual__2022-12-02T21:21:13.937226+00:00 [queued]>
[2022-12-02T21:21:14.624+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T21:21:14.625+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-02T21:21:14.626+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T21:21:14.635+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract_weather_api> on 2022-12-02 21:21:13.937226+00:00
[2022-12-02T21:21:14.641+0000] {standard_task_runner.py:55} INFO - Started process 5834 to run task
[2022-12-02T21:21:14.645+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'extract_dag', 'extract_weather_api', 'manual__2022-12-02T21:21:13.937226+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpthqg1f4e']
[2022-12-02T21:21:14.646+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask extract_weather_api
[2022-12-02T21:21:14.685+0000] {task_command.py:376} INFO - Running <TaskInstance: extract_dag.extract_weather_api manual__2022-12-02T21:21:13.937226+00:00 [running]> on host 94f969375df6
[2022-12-02T21:21:14.724+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_dag
AIRFLOW_CTX_TASK_ID=extract_weather_api
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T21:21:13.937226+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-02T21:21:13.937226+00:00
[2022-12-02T21:21:14.726+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-02T21:21:14.728+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'chmod -x /Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py && python /Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py']
[2022-12-02T21:21:14.736+0000] {subprocess.py:86} INFO - Output:
[2022-12-02T21:21:14.745+0000] {subprocess.py:93} INFO - chmod: cannot access '/Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py': No such file or directory
[2022-12-02T21:21:14.746+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-02T21:21:14.752+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-02T21:21:14.755+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_dag, task_id=extract_weather_api, execution_date=20221202T212113, start_date=20221202T212114, end_date=20221202T212114
[2022-12-02T21:21:14.762+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task extract_weather_api (Bash command failed. The command returned a non-zero exit code 1.; 5834)
[2022-12-02T21:21:14.777+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-02T21:21:14.793+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
