[2022-12-02T18:38:01.035+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract.extract_weather_api manual__2022-12-02T18:37:59.573040+00:00 [queued]>
[2022-12-02T18:38:01.041+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract.extract_weather_api manual__2022-12-02T18:37:59.573040+00:00 [queued]>
[2022-12-02T18:38:01.042+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T18:38:01.043+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-02T18:38:01.043+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T18:38:01.050+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract_weather_api> on 2022-12-02 18:37:59.573040+00:00
[2022-12-02T18:38:01.056+0000] {standard_task_runner.py:55} INFO - Started process 953 to run task
[2022-12-02T18:38:01.058+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'extract', 'extract_weather_api', 'manual__2022-12-02T18:37:59.573040+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpj0sw692l']
[2022-12-02T18:38:01.059+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask extract_weather_api
[2022-12-02T18:38:01.104+0000] {task_command.py:376} INFO - Running <TaskInstance: extract.extract_weather_api manual__2022-12-02T18:37:59.573040+00:00 [running]> on host 299b7b2f3c95
[2022-12-02T18:38:01.141+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract
AIRFLOW_CTX_TASK_ID=extract_weather_api
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T18:37:59.573040+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-02T18:37:59.573040+00:00
[2022-12-02T18:38:01.143+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-02T18:38:01.144+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py']
[2022-12-02T18:38:01.153+0000] {subprocess.py:86} INFO - Output:
[2022-12-02T18:38:01.207+0000] {subprocess.py:93} INFO - python: can't open file '/Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/extract.py': [Errno 2] No such file or directory
[2022-12-02T18:38:01.209+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-12-02T18:38:01.216+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-12-02T18:38:01.218+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=extract, task_id=extract_weather_api, execution_date=20221202T183759, start_date=20221202T183801, end_date=20221202T183801
[2022-12-02T18:38:01.226+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task extract_weather_api (Bash command failed. The command returned a non-zero exit code 2.; 953)
[2022-12-02T18:38:01.235+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-02T18:38:01.255+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
